spring:
  kafka:
    bootstrap-servers: http://172.16.2.201:9092,http://172.16.2.207:9092,http://172.16.2.210:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer