server:
  port: 8082

spring:
  profiles:
    active: service
  #数据源配置
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    # 使用druid数据源连接池
    type:  com.alibaba.druid.pool.DruidDataSource
    #加载驱动
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  kafka:
    bootstrap-servers: ${kafka.servers}
    consumer:
      group-id: ${kafka.groupid}

  application:
    # 指定注册到eureka server上的服务名称
    name: template-consumer
  
  # thymeleaf 配置
  thymeleaf:
    prefix: classpath:/thymeleaf/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
  mvc:
    # static 文件夹下的静态文件访问路径
    static-path-pattern: /**

  #配置mybatis
  mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.vedeng.template.domain
    configLocation: classpath*:mapper/*.xml


eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: ${eureka.client.service-url}
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

shiro:
  loginUrl: /login.html

  # Let Shiro Manage the sessions
  userNativeSessionManager: true

  # disable URL session rewriting
  sessionManager:
    sessionIdUrlRewritingEnabled: false

feign:
  hystrix:
    enabled: true