spring:
  kafka:
    bootstrap-servers: http://172.16.2.201:9092,http://172.16.2.207:9092,http://172.16.2.210:9092
    consumer:
      group-id: vedeng-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer